/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author tatip
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgPersona = new javax.swing.JDialog();
        fSGradientPanel2 = new LIB.FSGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCedulaDLG = new LIB.FSTexFieldMD();
        txtCorreoDlg = new LIB.FSTexFieldMD();
        txtDirecDLG = new LIB.FSTexFieldMD();
        txt1erNomDlg = new LIB.FSTexFieldMD();
        txt2doNomDLG = new LIB.FSTexFieldMD();
        txtTelfDLG = new LIB.FSTexFieldMD();
        txtFechaDlg = new com.toedter.calendar.JDateChooser();
        txt1erApeDLG = new LIB.FSTexFieldMD();
        txt2doApeDLG = new LIB.FSTexFieldMD();
        rdbMasculinoDlg = new javax.swing.JRadioButton();
        rdbFemeninoDlg = new javax.swing.JRadioButton();
        rdbOtroDlg = new javax.swing.JRadioButton();
        btnRetrocederDlgRegistro = new LIB.FSButtonMD();
        btnSiguienteDlgUsu = new LIB.FSButtonMD();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fSTexFieldMD1 = new LIB.FSTexFieldMD();
        fSPasswordFieldMD1 = new LIB.FSPasswordFieldMD();
        fSButtonMD1 = new LIB.FSButtonMD();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        fSGradientPanel2.setFSEndColor(new java.awt.Color(0, 51, 153));
        fSGradientPanel2.setFSStartColor(new java.awt.Color(0, 51, 51));

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Registro de Usuarios");

        javax.swing.GroupLayout fSGradientPanel2Layout = new javax.swing.GroupLayout(fSGradientPanel2);
        fSGradientPanel2.setLayout(fSGradientPanel2Layout);
        fSGradientPanel2Layout.setHorizontalGroup(
            fSGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fSGradientPanel2Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        fSGradientPanel2Layout.setVerticalGroup(
            fSGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fSGradientPanel2Layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnCedulaDLG.setForeground(new java.awt.Color(0, 102, 255));
        btnCedulaDLG.setToolTipText("Ingresa tu cédula");
        btnCedulaDLG.setBordeColorFocus(new java.awt.Color(0, 102, 255));
        btnCedulaDLG.setPlaceholder("Cédula");

        txtCorreoDlg.setForeground(new java.awt.Color(0, 102, 255));
        txtCorreoDlg.setToolTipText("Ingresa tu cédula");
        txtCorreoDlg.setBordeColorFocus(new java.awt.Color(0, 102, 255));
        txtCorreoDlg.setPlaceholder("Correo Electrónico");
        txtCorreoDlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoDlgActionPerformed(evt);
            }
        });

        txtDirecDLG.setForeground(new java.awt.Color(0, 102, 255));
        txtDirecDLG.setToolTipText("Ingresa tu cédula");
        txtDirecDLG.setBordeColorFocus(new java.awt.Color(0, 102, 255));
        txtDirecDLG.setPlaceholder("Dirección");
        txtDirecDLG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirecDLGActionPerformed(evt);
            }
        });

        txt1erNomDlg.setForeground(new java.awt.Color(0, 102, 255));
        txt1erNomDlg.setToolTipText("Ingresa tu cédula");
        txt1erNomDlg.setBordeColorFocus(new java.awt.Color(0, 102, 255));
        txt1erNomDlg.setPlaceholder("Primer Nombre");

        txt2doNomDLG.setForeground(new java.awt.Color(0, 102, 255));
        txt2doNomDLG.setToolTipText("Ingresa tu cédula");
        txt2doNomDLG.setBordeColorFocus(new java.awt.Color(0, 102, 255));
        txt2doNomDLG.setPlaceholder("Segundo Nombre");

        txtTelfDLG.setForeground(new java.awt.Color(0, 102, 255));
        txtTelfDLG.setToolTipText("Ingresa tu cédula");
        txtTelfDLG.setBordeColorFocus(new java.awt.Color(0, 102, 255));
        txtTelfDLG.setPlaceholder("Teléfono");
        txtTelfDLG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelfDLGActionPerformed(evt);
            }
        });

        txt1erApeDLG.setForeground(new java.awt.Color(0, 102, 255));
        txt1erApeDLG.setToolTipText("Ingresa tu cédula");
        txt1erApeDLG.setBordeColorFocus(new java.awt.Color(0, 102, 255));
        txt1erApeDLG.setPlaceholder("Primer Apellido");
        txt1erApeDLG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1erApeDLGActionPerformed(evt);
            }
        });

        txt2doApeDLG.setForeground(new java.awt.Color(0, 102, 255));
        txt2doApeDLG.setToolTipText("Ingresa tu cédula");
        txt2doApeDLG.setBordeColorFocus(new java.awt.Color(0, 102, 255));
        txt2doApeDLG.setPlaceholder("Segundo Apellido");
        txt2doApeDLG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2doApeDLGActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbMasculinoDlg);
        rdbMasculinoDlg.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        rdbMasculinoDlg.setForeground(new java.awt.Color(0, 51, 204));
        rdbMasculinoDlg.setText("Masculino");

        buttonGroup1.add(rdbFemeninoDlg);
        rdbFemeninoDlg.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        rdbFemeninoDlg.setForeground(new java.awt.Color(0, 51, 204));
        rdbFemeninoDlg.setText("Femenino");

        buttonGroup1.add(rdbOtroDlg);
        rdbOtroDlg.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        rdbOtroDlg.setForeground(new java.awt.Color(0, 51, 204));
        rdbOtroDlg.setText("Otro");
        rdbOtroDlg.setActionCommand("");

        btnRetrocederDlgRegistro.setBackground(new java.awt.Color(255, 255, 255));
        btnRetrocederDlgRegistro.setForeground(new java.awt.Color(0, 0, 0));
        btnRetrocederDlgRegistro.setText("Retroceder");
        btnRetrocederDlgRegistro.setToolTipText("Regresar al inicio de sesión");
        btnRetrocederDlgRegistro.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnRetrocederDlgRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederDlgRegistroActionPerformed(evt);
            }
        });

        btnSiguienteDlgUsu.setBackground(new java.awt.Color(255, 255, 255));
        btnSiguienteDlgUsu.setForeground(new java.awt.Color(0, 0, 0));
        btnSiguienteDlgUsu.setText("Siguiente");
        btnSiguienteDlgUsu.setToolTipText("Continua con tu registro");
        btnSiguienteDlgUsu.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnSiguienteDlgUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteDlgUsuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSiguienteDlgUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRetrocederDlgRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt2doApeDLG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCedulaDLG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt1erNomDlg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt2doNomDLG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt1erApeDLG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaDlg, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreoDlg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rdbMasculinoDlg)
                                .addGap(18, 18, 18)
                                .addComponent(rdbFemeninoDlg)
                                .addGap(18, 18, 18)
                                .addComponent(rdbOtroDlg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtDirecDLG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelfDLG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCedulaDLG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreoDlg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1erNomDlg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirecDLG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt2doNomDLG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelfDLG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt1erApeDLG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaDlg, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt2doApeDLG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbMasculinoDlg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbFemeninoDlg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbOtroDlg, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguienteDlgUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetrocederDlgRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgPersonaLayout = new javax.swing.GroupLayout(dlgPersona.getContentPane());
        dlgPersona.getContentPane().setLayout(dlgPersonaLayout);
        dlgPersonaLayout.setHorizontalGroup(
            dlgPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fSGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgPersonaLayout.setVerticalGroup(
            dlgPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgPersonaLayout.createSequentialGroup()
                .addComponent(fSGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mete Gol Gana");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        fSTexFieldMD1.setForeground(new java.awt.Color(0, 102, 255));
        fSTexFieldMD1.setToolTipText("Ingresa tu cédula");
        fSTexFieldMD1.setBordeColorFocus(new java.awt.Color(0, 102, 255));
        fSTexFieldMD1.setPlaceholder("Usuario");
        jPanel2.add(fSTexFieldMD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        fSPasswordFieldMD1.setForeground(new java.awt.Color(51, 102, 255));
        fSPasswordFieldMD1.setToolTipText("Ingresa tu contraseña");
        fSPasswordFieldMD1.setBordeColorFocus(new java.awt.Color(0, 102, 255));
        fSPasswordFieldMD1.setPlaceholder("Contraseña ");
        jPanel2.add(fSPasswordFieldMD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        fSButtonMD1.setBackground(new java.awt.Color(255, 255, 255));
        fSButtonMD1.setForeground(new java.awt.Color(0, 102, 255));
        fSButtonMD1.setText("Ingresar");
        fSButtonMD1.setToolTipText("Inicia Sesión");
        fSButtonMD1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        fSButtonMD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSButtonMD1ActionPerformed(evt);
            }
        });
        jPanel2.add(fSButtonMD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 250, -1));

        jComboBox1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 102, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingresar Como:", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setToolTipText("Tipo de usuario");
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 250, 39));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¿Olvedaste tu contraseña?");
        jLabel2.setToolTipText("Restablece tu contraseña");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cancha.png"))); // NOI18N
        jLabel4.setToolTipText("Cerrar programa");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 610));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Inicio de Sesión");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistash/iconos/iconosh/cancha.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fSButtonMD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSButtonMD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fSButtonMD1ActionPerformed

    private void txtTelfDLGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelfDLGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelfDLGActionPerformed

    private void txtDirecDLGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirecDLGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirecDLGActionPerformed

    private void btnSiguienteDlgUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteDlgUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteDlgUsuActionPerformed

    private void txt2doApeDLGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2doApeDLGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2doApeDLGActionPerformed

    private void txtCorreoDlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoDlgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoDlgActionPerformed

    private void btnRetrocederDlgRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederDlgRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetrocederDlgRegistroActionPerformed

    private void txt1erApeDLGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1erApeDLGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1erApeDLGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSTexFieldMD btnCedulaDLG;
    private LIB.FSButtonMD btnRetrocederDlgRegistro;
    private LIB.FSButtonMD btnSiguienteDlgUsu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog dlgPersona;
    private LIB.FSButtonMD fSButtonMD1;
    private LIB.FSGradientPanel fSGradientPanel2;
    private LIB.FSPasswordFieldMD fSPasswordFieldMD1;
    private LIB.FSTexFieldMD fSTexFieldMD1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rdbFemeninoDlg;
    private javax.swing.JRadioButton rdbMasculinoDlg;
    private javax.swing.JRadioButton rdbOtroDlg;
    private LIB.FSTexFieldMD txt1erApeDLG;
    private LIB.FSTexFieldMD txt1erNomDlg;
    private LIB.FSTexFieldMD txt2doApeDLG;
    private LIB.FSTexFieldMD txt2doNomDLG;
    private LIB.FSTexFieldMD txtCorreoDlg;
    private LIB.FSTexFieldMD txtDirecDLG;
    private com.toedter.calendar.JDateChooser txtFechaDlg;
    private LIB.FSTexFieldMD txtTelfDLG;
    // End of variables declaration//GEN-END:variables
}
